### ISSUE TITLE
convert eml to html error

### ISSUE THREAD

**Issue by lizhiwei888** [amitevski/eml_to_html#1]
eml_to_html/node_modules/mailparser/lib/mailparser.js:1407
        defaultExt = mime.extension(contentType);
                          ^

TypeError: mime.extension is not a function
    at MailParser._generateFileName (/Users/moka/nodejs/eml_to_html/node_modules/mailparser/lib/mailparser.js:1407:27)
    at MailParser._processStateHeader (/Users/moka/nodejs/eml_to_html/node_modules/mailparser/lib/mailparser.js:309:61)
    at MailParser._process (/Users/moka/nodejs/eml_to_html/node_modules/mailparser/lib/mailparser.js:227:22)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

**Comment by lizhiwei888** [comment]
I changed mailparser version from 0.4.6 to 0.6.2 is ok

**Comment by amitevski** [comment]
Awesome! Do you want to create a pull request?

**Comment by call0fcode** [comment]
It also worked for me! For those having this problem, simply run `npm i mailparser@0.6.2` on the terminal (from project's root directory) and _mailparser_ will be updated to version 0.6.2.

I'm going to make a pull request so that the mailparser dependency is always downloaded in the correct version, 0.6.2.

**Comment by webbrain-one** [comment]
Hi! 👋

I've opened [PR #5](https://github.com/amitevski/eml_to_html/pull/5) to address this. It fixes the `TypeError: mime.extension is not a function` error you reported.

Hope this helps!
